version: "3.7"
services:
  short-url:
    build:
      context: .
      args:
        MIX_ENV: "${MIX_ENV}"
        RELEASE_ENV: "${RELEASE_ENV}"
        DATABASE_URL: "${DATABASE_URL}"
        SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    image: image/short-url
    depends_on:
      short-url-db:
        condition: service_healthy
    restart: on-failure
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: "${MIX_ENV}"
      RELEASE_ENV: "${RELEASE_ENV}"
      DATABASE_URL: "${DATABASE_URL}"

  short-url-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
