version: "3.7"
services:
  short-url:
    build:
      target: base
      args:
        MIX_ENV: "${MIX_ENV}"
        RELEASE_ENV: "${RELEASE_ENV}"
        DATABASE_URL: "${DATABASE_URL}"
        SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    image: image/short-url-base
    depends_on:
      - short-url-db    
    environment:
      MIX_ENV: "${MIX_ENV}"
      RELEASE_ENV: "${RELEASE_ENV}"
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
